# Generated by Django 3.2.8 on 2022-05-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='city',
            field=models.CharField(db_column='city', max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='country',
            field=models.CharField(db_column='country', max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='state',
            field=models.CharField(db_column='state', max_length=50, null=True, verbose_name='State'),
        ),
    ]
