# Generated by Django 3.2.8 on 2022-05-23 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Send_msg',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('latt', models.BigIntegerField(db_column='latt', verbose_name='Latt')),
                ('longt', models.BigIntegerField(db_column='longt', verbose_name='Longt')),
                ('whom', models.CharField(db_column='whom', max_length=50, verbose_name='Whom')),
                ('content', models.TextField(db_column='content', max_length=100, null=True, verbose_name='Content')),
                ('message', models.TextField(db_column='message', max_length=100, null=True, verbose_name='Message')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Send_msg',
            },
        ),
    ]
