# Generated by Django 3.2.8 on 2022-05-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_msg',
            name='latt',
            field=models.FloatField(db_column='latt', verbose_name='Latt'),
        ),
        migrations.AlterField(
            model_name='send_msg',
            name='longt',
            field=models.FloatField(db_column='longt', verbose_name='Longt'),
        ),
    ]
