# Generated by Django 3.2.8 on 2022-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20220523_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_msg',
            name='key',
            field=models.CharField(db_column='key', max_length=100, null=True, verbose_name='Key'),
        ),
    ]
