# Generated by Django 3.2.8 on 2022-05-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_send_msg_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_msg',
            name='content',
            field=models.TextField(db_column='content', max_length=500, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='send_msg',
            name='key',
            field=models.CharField(db_column='key', max_length=500, null=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='send_msg',
            name='latt',
            field=models.CharField(db_column='latt', max_length=500, verbose_name='Latt'),
        ),
        migrations.AlterField(
            model_name='send_msg',
            name='longt',
            field=models.CharField(db_column='longt', max_length=500, verbose_name='Longt'),
        ),
        migrations.AlterField(
            model_name='send_msg',
            name='message',
            field=models.TextField(db_column='message', max_length=500, null=True, verbose_name='Message'),
        ),
    ]
