# Generated by Django 3.2.8 on 2022-05-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20220524_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_msg',
            name='accept',
            field=models.CharField(db_column='accept', max_length=50, null=True, verbose_name='Accept'),
        ),
    ]
